Enable `no_std` support via a default-enabled `std` feature flag.
ZcashFoundation/redjubjub pull request #205
Opened 2024-12-18 19:06 UTC by nuttycom

2024-12-18 19:07 UTC, nuttycom commented on Cargo.toml
> +edition = "2021"
This change does not change the MSRV, as `reddsa 0.5.0` already requires `1.65`.

2024-12-18 19:41 UTC, str4d requested changes
Reviewed 96c0b799b72d324b35afb1ea90cdc52150e29ce8.

2024-12-18 19:41 UTC, str4d commented on Cargo.toml
>  serde = { version = "1", optional = true, features = ["derive"] }
This should also have `default-features = false` to ensure that enabling the `serde` feature flag doesn't force `std` to also be enabled.

2024-12-18 19:47 UTC, str4d approved these changes
utACK e413019904400f4caa3550df7c4040befadfbb14

2024-12-26 17:40 UTC, conradoplg approved these changes

2024-12-26 17:41 UTC, merged